Repository whpu-aa/website, pull requests merged in 2020-08, with the labels that each got.

#10 初始化CI
  .github/workflows/ci.yaml
Labels: infrastructure

#9 轮播器组件
  src/components/Carousel.vue
Labels: enhancement

#17 让CI使用Cache
  .github/workflows/ci.yaml
Labels: infrastructure

#18 开发AppBar。
  src/App.vue
  src/components/AppBar.vue
Labels: enhancement

#22 现在CI的lint命令不会自动修复错误，而是会报错。
  .github/workflows/ci.yaml
  package.json
Labels: bug, infrastructure

#23 添加了常用的vscode配置文件。
  .gitignore
  .vscode/extensions.json
  .vscode/settings.json
Labels: infrastructure

#27 增加可用来跳转的组件，组件内容为图片加文本。修改新闻文章组件中部分样式并添加其他新闻部分
  src/components/MoreArticleItem.vue
  src/views/NewsArticles.vue
Labels: enhancement
